# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of Company', max_length=400, verbose_name='Name')),
                ('description', models.TextField(help_text='An overview of the company', max_length=1500, verbose_name='Description')),
                ('website', models.URLField(blank=True, help_text="company's website", max_length=400, null=True, verbose_name='Website')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
