# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 19:28
from __future__ import unicode_literals

from django.db import migrations


def make_initial_companies(apps, schema_editor):
    '''
    '''
    Company = apps.get_model('companies', 'Company')
    Company.objects.bulk_create([
        Company(
            name='Company A',
            description='Description for Company A',
            website='company_a.com'
        ),
        Company(
            name='Company B',
            description='Description for Company B',
            website='company_b.com'
        ),
        Company(
            name='Company C',
            description='Description for Company C',
            website='company_c.com'
        ),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_initial_companies)
    ]
